version: '3'
services:
  frontend:
    image: ahmedhanzala01/frontend-app:v1
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: ahmedhanzala01/backend-app:v1
    ports:
      - "3000:3000"
